/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Author: Ervinas (https://sketchfab.com/paulauskaservinas2018)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/flying-drone-animation-3d24cf2b6c5d4dc78bbaca4fcdce5c0a
    Title: Flying Drone animation
    */

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

// Model dosyasının DOĞRU ve TEK yolu
const modelPath = "/models/drone/scene-transformed.glb";

export function Model(props) {
  const group = useRef();

  // Modeli SADECE BİR KEZ, doğru yoldan yüklüyoruz.
  const { scene, animations } = useGLTF(modelPath);

  // Animasyonları kuruyoruz
  const { actions } = useAnimations(animations, group);

  // Modelin animasyonunu başlatıyoruz
  useEffect(() => {
    // 'actions' içindeki ilk animasyonu bul ve oynat
    const firstAnimationName = Object.keys(actions)[0];
    if (firstAnimationName) {
      actions[firstAnimationName].play();
    }
  }, [actions]);

  // Yüklenen sahneyi doğrudan 'primitive' ile render ediyoruz.
  // Bu, en temiz ve hatasız yöntemdir.
  return <primitive ref={group} object={scene} {...props} dispose={null} />;
}

// Modeli önceden yüklerken de DOĞRU yolu kullanıyoruz.
useGLTF.preload(modelPath);
